export const serviceCategories = [
  {
    id: 1,
    name: "Home Service",
    image: "/home-icon.png",
    iconColor: "text-blue-600",
  },
  {
    id: 2,
    name: "Professionals",
    image: "/professionals-icon.png",
    iconColor: "text-green-600",
  },
  {
    id: 3,
    name: "Medicine",
    image: "/medicine-icon.png",
    iconColor: "text-green-600",
  },
  {
    id: 4,
    name: "Administration",
    image: "/administration-icon.png",
    iconColor: "text-green-600",
  },
  {
    id: 5,
    name: "Engineering",
    image: "/engineer-icon.png",
    iconColor: "text-blue-600",
  },
  {
    id: 6,
    name: "Home Service",
    image: "/home-icon.png",
    iconColor: "text-blue-600",
  },
  {
    id: 7,
    name: "Professionals",
    image: "/professionals-icon.png",
    iconColor: "text-green-600",
  },
  {
    id: 8,
    name: "Medicine",
    image: "/medicine-icon.png",
    iconColor: "text-green-600",
  },
  {
    id: 9,
    name: "Administration",
    image: "/administration-icon.png",
    iconColor: "text-green-600",
  },
  {
    id: 10,
    name: "Engineering",
    image: "/engineer-icon.png",
    iconColor: "text-blue-600",
  },
  {
    id: 11,
    name: "Engineering",
    image: "/engineer-icon.png",
    iconColor: "text-blue-600",
  },
  {
    id: 12,
    name: "Home Service",
    image: "/home-icon.png",
    iconColor: "text-blue-600",
  },
  {
    id: 13,
    name: "Professionals",
    image: "/professionals-icon.png",
    iconColor: "text-green-600",
  },
  {
    id: 14,
    name: "Medicine",
    image: "/medicine-icon.png",
    iconColor: "text-green-600",
  },
  {
    id: 15,
    name: "Administration",
    image: "/administration-icon.png",
    iconColor: "text-green-600",
  },
];
