export const adsBannerData = [
  {
    id: 0,
    key: 0,
    serial: 1,
    name: "Khalid Endak",
    email: "khalidendak@gmail.com",
    phoneNumber: "+91126",
    date: "11 Sep, 2025",
    status: "Inactive",
    image: "/banner-image.png",
  },
  {
    id: 1,
    key: 1,
    serial: 2,
    name: "Ayesha Khan",
    email: "ayeshakhan@gmail.com",
    phoneNumber: "+9112655423",
    date: "12 Sep, 2025",
    status: "Active",
    image: "/banner-image.png",
  },
  {
    id: 2,
    key: 2,
    serial: 3,
    name: "Omar Farooq",
    email: "omarfarooq@gmail.com",
    phoneNumber: "+91126",
    date: "13 Sep, 2025",
    status: "Inactive",
    image: "/banner-image.png",
  },
  {
    id: 3,
    key: 3,
    serial: 4,
    name: "Sara Malik",
    email: "saramalik@gmail.com",
    phoneNumber: "+9112655423",
    date: "14 Sep, 2025",
    status: "Active",
    image: "/banner-image.png",
  },
  {
    id: 4,
    key: 4,
    serial: 5,
    name: "Imran Qureshi",
    email: "imranqureshi@gmail.com",
    phoneNumber: "+91126",
    date: "15 Sep, 2025",
    status: "Inactive",
    image: "/banner-image.png",
  },
  {
    id: 5,
    key: 5,
    serial: 6,
    name: "Fatima Sheikh",
    email: "fatimasheikh@gmail.com",
    phoneNumber: "+9112655423",
    date: "16 Sep, 2025",
    status: "Active",
    image: "/banner-image.png",
  },
  {
    id: 6,
    key: 6,
    serial: 7,
    name: "Zahid Ali",
    email: "zahidali@gmail.com",
    phoneNumber: "+91126",
    date: "17 Sep, 2025",
    status: "Inactive",
    image: "/banner-image.png",
  },
  {
    id: 7,
    key: 7,
    serial: 8,
    name: "Maryam Noor",
    email: "maryamnoor@gmail.com",
    phoneNumber: "+9112655423",
    date: "18 Sep, 2025",
    status: "Active",
    image: "/banner-image.png",
  },
  {
    id: 8,
    key: 8,
    serial: 9,
    name: "Bilal Ahmed",
    email: "bilalahmed@gmail.com",
    phoneNumber: "+91126",
    date: "19 Sep, 2025",
    status: "Inactive",
    image: "/banner-image.png",
  },
  {
    id: 9,
    key: 9,
    serial: 10,
    name: "Hina Raza",
    email: "hinaraza@gmail.com",
    phoneNumber: "+9112655423",
    date: "20 Sep, 2025",
    status: "Active",
    image: "/banner-image.png",
  },
];
